<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hrm.Domain\Hrm.Domain.csproj" />
    <ProjectReference Include="..\..\..\jarvis\frameworks\Jarvis.ORM.EntityFramework\Jarvis.ORM.EntityFramework.csproj" />
    <ProjectReference Include="..\..\..\jarvis\frameworks\Jarvis.Caching\Jarvis.Caching.csproj" />
    <ProjectReference Include="..\..\..\jarvis\frameworks\Jarvis.BlobStoring\Jarvis.BlobStoring.csproj" />
  </ItemGroup>

</Project>
